### ISSUE TITLE
N-dimensional input? 

### ISSUE THREAD

**Issue by sprungj** [harveydevereux/AlphaShapes.jl#13]
Readme says input array can be D-dimensional points, but `AlphaShape` function seems to enforce 2 dimensions:
> `X::AbstractArray{Float64,2}`

Unless I am misreading?

**Comment by harveydevereux** [comment]
Apologies for the delay @sprungj 

Yes the readme is wrong here - points in main must be 2 dimensional.

In principal 3D + *should* work if the functions are updated if I recall correctly, in fact 3D was working in the dev branch https://github.com/harveydevereux/AlphaShapes.jl/tree/dev

I need to merge some optimisations that change the API as well into a new release.

I shall address this soon, along with that, and perhaps include 3d and see if Nd will work.

**Comment by harveydevereux** [comment]
@sprungj thanks for flagging, readme is updated. Will also see if N-D can be achieved for a 0.4.0 release, should be as MiniQhull.jl does

- PR #14 will addressed the incorrect readme 
- dev branch will be rebased/updated as well to produce a 0.4.0 release that also supports N-D

**Comment by sprungj** [comment]
Thanks for the update -- looking forward to 0.4.0!
