### ISSUE TITLE
Register Package?

### ISSUE THREAD

**Issue by itsdfish** [harveydevereux/AlphaShapes.jl#2]
Greetings,

I came across your package while searching for a way to estimate the volume of arbitrary n-dimensional shapes. Thank you for putting it together. I was wondering if you would be willing to register your package and add [CompatHelper](https://github.com/JuliaRegistries/CompatHelper.jl) to keep dependencies up to date?

**Comment by harveydevereux** [comment]
Hi, 

Thanks for the interest! I think it's already registered (https://github.com/JuliaRegistries/General/tree/master/A/AlphaShapes) so you should be able to install it from Pkg.jl.

I'll start a branch to add CompatHelper (https://github.com/harveydevereux/AlphaShapes.jl/tree/adds_compathelper), thanks for the suggestion. 

Hopefully I'll get round to it this week, but feel free to contribute.

**Comment by itsdfish** [comment]
My mistake. I submitted a pull request that will add CompatHelper along with CI and a badge that will show the latest registered version. 

I do have a question about a slightly different issue. One missing feature in this package is the ability to identity the intersection between two shapes. Do you have any plans to add such a feature, or what it might entail? I wonder if it would be a matter of passing the relevant information to existing functions in Polyhedra.jl.

**Comment by harveydevereux** [comment]
Great thanks, I'll take a look in a second.

Just had a look at Polyhedra.jl, looks like workflow would be Vertices::Array{Float64,3} -> "convex hull points" -> Polyhedra::vrep for both shapes then it should just be a call to intersect(P1,P2) like this example from their docs. Have not used Polyhedra myself so could be wrong.

```julia
# two hard coded polygons
P1 = polyhedron(vrep([
    -1.9 -1.7
    -1.8  0.5
     1.7  0.7
     1.9 -0.3
     0.9 -1.1
]), lib)

P2 = polyhedron(vrep([
    -2.5 -1.1
    -0.8  0.8
     0.1  0.9
     1.8 -1.2
     1.3  0.1
]), lib)

Pint = intersect(P1, P2) # the intersection shape


If this is the case it should be simple..
```

**Comment by harveydevereux** [comment]
Closing and moving over to new issue https://github.com/harveydevereux/AlphaShapes.jl/issues/4
